### ISSUE TITLE
typos in .sh scripts

### ISSUE THREAD

**Issue by RAWWiberg** [FemeniasM/ExplorATE_shell_script#3]
Hello again,

I spotted some typos in the `.sh` scripts in the `bin/` folder that were causing some errors.

Specifically, when assigning the `salmon_path` variable, there was an extra "=" character which meant `bash` could not find the `salmon` command (because it was looking for `"=salmon"` instead of `"salmon"`.

I took the liberty of forking your repo and fixing this. I've made a pull request for you.

Best wishes,

**Comment by FemeniasM** [comment]
Dear @RAWWiberg 
I checked your edits, I really appreciate your help! I've been quite busy in the last few months, but I hope to improve the code over time and make it as useful as possible for users. Your contribution will certainly always be welcome, 
best regards

**Comment by RAWWiberg** [comment]
Hello,

No problem at all. I really like the idea of ExplorATE so I wanted to give it a try immediately. And it's rare that I find an issue that I can help fix, so I am very glad to be able to help.

Looking forward to seeing how ExplorATE develops :)

Best wishes,
Axel
------- Original Message -------
